/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
#if 0
	__asm volatile("LDR R1,=#0x20001000");
	__asm volatile("LDR R2,=#0x20001004");
	__asm volatile("LDR R0, [R1]");
	__asm volatile("LDR R1, [R2]");
	__asm volatile("ADD R0, R0, R1");
	__asm volatile("STR R0, [R2]");
#endif

	int val = 50;
	__asm volatile("MOV R0, %0": : "r"(val));

	int control_reg;
	/*Read CONTROL register to control_reg */
	__asm volatile("MRS %0, CONTROL": "=r"(control_reg) );

	int var1 = 10, var2;

	__asm ("MOV %0,%1": "=r"(var2): "r"(var1));  //Copy the content of 'C' variable var1 to var2

	int p1, *p2;

	p2 = (int*)0x20000008;

	__asm volatile("LDR %0, [%1]": "=r"(p1): "r"(p2)); //p1 = *p2


	for(;;);
}
